In [8]:
import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

#Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

"""У функции reshape есть дополнительный именованный аргумент order. 
Он задаёт принцип, по которому элементы заполняют массив новой формы. 
Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше.
Если order='F', массив заполняется числами по столбцам:"""
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

"""Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование.
Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.
Будем работать с двумерным массивом:"""
arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
#Let`s transpose it
arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])

#При транспонировании одномерного массива его форма не меняется:
arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)
# (3,)

(3,)
(3,)


In [15]:
#Создадим массив из шести чисел:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

#Обратиться к его элементу по индексу можно так же, как и к списку:
print(arr[2])
# 1.4

#Привычная запись для срезов работает и для одномерных массивов:
print(arr[2:4])
# [1.4 1.6]

#Наконец, напечатать массив в обратном порядке можно с помощью привычной конструкции [::-1]:
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

#С многомерными массивами работать немного интереснее. Создадим двумерный массив из одномерного:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

#Можно воспользоваться привычной записью нескольких индексов в нескольких квадратных скобках:
nd_array[1][2]
# 3.0
nd_array[1, 2]
# 3.0

#Как видите, получилось то же самое число. Также через запятую можно передавать срезы или даже их комбинации с индексами. 
# Например, получим все элементы из колонки 3 для первых двух строк:
nd_array[:2, 2]
# array([1., 3.])

#Несмотря на то что в массиве этот срез является столбцом, вместо него мы получили одномерный массив в виде строки.
#Можно применять срезы сразу и к строкам, и к столбцам:
nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

#Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие. 
# Например, из всех строк получим срез с третьего по четвёртый столбцы:
nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

#Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно.
#Строки будут получены целиком по умолчанию:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


array([1., 3.])

In [ ]:
try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]
# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]
# В переменную line_4 сохраните строку 4
line_4 = mystery[3]
# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]
# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# Результат сохраните в переменную part
part = mystery[1:4, 2:5]
#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, -1]
# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()

In [3]:
"""СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ
Иногда возникает задача по сортировке значений в массиве. Для её решения существуют встроенная в NumPy функция sort.
Она обладает дополнительными параметрами, в том числе возможностью сортировки многомерных массивов, 
однако пока что это нам не потребуется. Применять функцию можно двумя способами."""
import numpy as np
#Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]
#Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]


[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]
None
[ 3  4 12 12 15 23 23 45]


In [ ]:
import numpy as np
"""РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ"""
#Начнём с примера — создадим массив:
data = np.array([4, 9, -4, 3])
#Воспользуемся встроенной в NumPy функцией sqrt, чтобы посчитать квадратные корни из элементов.
roots = np.sqrt(data)
roots
# RuntimeWarning: invalid value encountered in sqrt
# array([2.        , 3.        ,        nan, 1.73205081])
"""NumPy выдал предупреждение о том, что в функцию sqrt попало некорректное значение.
# Это было число -4, а как вы помните, корень из отрицательного числа в действительных числах не берётся.
# Однако программа не сломалась окончательно, а продолжила работу. На том месте, 
# где должен был оказаться корень из -4, теперь присутствует объект nan. 
# Он расшифровывается как Not a number (не число). Этот объект аналогичен встроенному типу None, 
# но имеет несколько отличий:"""

#Отличие 1. None является отдельным объектом типа NoneType. np.nan — это отдельный представитель класса float:
print(type(None))
# <class 'NoneType'>
print(type(np.nan))
# <class 'float'>
type(np.nan)

#Отличие 2. None могут быть равны друг другу, а np.nan — нет:
print(None == None)
# True
print(np.nan == np.nan)
# False
#Как вы помните, чтобы грамотно сравнить что-либо с None, необходимо использовать оператор is.
# Это ещё более актуально для np.nan. Однако None даже через is не является эквивалентным np.nan:

print(None is None)
# True
print(np.nan is np.nan)
# True
print(np.nan is None)
# False
"""Иногда работать с отсутствующими данными всё же нужно. 
# Они могут возникнуть не только потому, что мы применили функцию к некорректному аргументу. 
# Например, при анализе вакансий на сайте для некоторых из них может быть не указана зарплата,
# но при этом нам необходимо проанализировать статистику по зарплатам на сайте. 
# Если попробовать посчитать сумму массива, который содержит np.nan, в итоге получится nan:"""

sum(roots)
# nan

#Что же делать?
#Можно заполнить пропущенные значения, например, нулями. 
# Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»:

np.isnan(roots)
# array([False, False,  True, False])
#Можно использовать полученный массив из True и False для извлечения элементов из массива roots,
#на месте которых в булевом массиве указано True. 
#Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:

roots[np.isnan(roots)]
# array([nan])
#Этим элементам можно присвоить новые значения, например 0:

roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081])
#После этого, если пропущенных значений больше нет, можем подсчитать сумму элементов массива:

sum(roots)
# 6.732050807568877
#Ранее проблема при подсчёте суммы элементов в массиве roots возникала из-за того, 
# что отсутствовало значение для квадратного корня из -4 — вместо него было указано np.nan. 
# Сумма элементов массива, содержащего nan, также является nan. 
# Поэтому приходится заменить nan, например, на 0, чтобы подсчитать сумму элементов массива.

In [ ]:
try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery
import numpy as np
# Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено
nans_index = np.isnan(mystery)
# В переменную n_nan сохраните число пропущенных значений
n_nan = sum(nans_index)
# Заполните пропущенные значения в массиве mystery нулями
mystery[nans_index] = 0
# Поменяйте тип данных в массиве mystery на int32
mystery = np.int32(mystery)
# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = np.sort(mystery)
# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = array.reshape((5,3), order='F')
#  Сохраните в переменную col столбец 2
col = table[:, 1]