In [19]:
import numpy as np

def get_unique_loto(num):
    sample = np.arange(1, 101)
    res = list()
    for i in range(num):
        res.append(np.random.choice(sample, replace=False, size=(5, 5)))
    res = np.array(res)
    return res

get_unique_loto(5)

array([[[21,  7, 32, 28, 43],
        [29, 83, 15, 96, 86],
        [84, 78, 11, 27, 91],
        [81, 88, 93, 47, 35],
        [37, 16, 10, 98, 22]],

       [[14, 19, 16, 20, 31],
        [91, 11, 49, 73, 99],
        [98, 55, 70,  9, 47],
        [83, 15, 39, 32, 52],
        [53, 42, 78, 41, 71]],

       [[37,  1, 25, 75,  6],
        [22, 24, 29, 23, 62],
        [40, 27, 61, 77, 31],
        [32, 93, 81, 73, 41],
        [17, 85,  3, 10, 26]],

       [[72, 91, 59, 41, 27],
        [48, 49, 68, 21, 73],
        [69, 78, 65, 51, 17],
        [45, 38, 60, 20, 92],
        [56, 28, 30, 75, 12]],

       [[23, 87, 14, 91, 57],
        [ 1, 92, 59, 20, 27],
        [ 2, 36, 54, 72, 13],
        [45, 74, 49, 17, 95],
        [26, 18, 46, 69, 60]]])

In [17]:
import numpy as np

#loto_example = np.random.randint(0, 100, size=(3, 5, 5))
#unique_loto = np.random.choice(loto_example, size=3, replace=False)
list_1 = []
sample = np.arange(1, 101)
new = np.random.choice(sample, replace=False, size=(5, 5))
list_1.append (new)
print (sample)
print (new)
print (list_1)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[95 40 32 60  3]
 [22 38 64 69 36]
 [27 39 18  5 13]
 [34 33 80 19  6]
 [35 47  8 44 93]]
[array([[95, 40, 32, 60,  3],
       [22, 38, 64, 69, 36],
       [27, 39, 18,  5, 13],
       [34, 33, 80, 19,  6],
       [35, 47,  8, 44, 93]])]
