In [ ]:
#Произведём сложение двух векторов:

import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2
# array([14. , 10. , 10.6, 15.5])
#Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2
# [2, 4, 7, 2.5, 12, 6, 3.6, 13]
#Чтобы сложить два этих списка поэлементно, нам пришлось бы написать списочное сокращение с применением функции zip():
[x + y for x, y in zip(list1, list2)]
# [14, 10, 10.6, 15.5]

#Для совершения арифметических операций с векторами они должны быть одинаковой длины.
#Поэлементно умножим два вектора одинаковой длины:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2
# array([24. , 24. , 25.2, 32.5])
#А теперь создадим vec2, который будет на один элемент короче, чем vec1:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6])
vec1 * vec2
# ValueError: operands could not be broadcast together with shapes (4,) (3,)
# Ошибка значения: операнд не может быть распространён одновременно на структуры с формами (4,) и (3,).
#Возникла ValueError.

#Исключением является случай, когда операция происходит с вектором и одним числом. Например, вектор целиком можно умножить на число или возвести в степень этого числа:
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

#Также векторы можно сравнивать друг с другом поэлементно:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2
# array([False, False,  True, False])
#В результате получаем вектор исходной длины из булевых переменных, 
# которые соответствуют результату поэлементного сравнения чисел из двух векторов.
#Аналогично можно сравнивать вектор с числом:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])

In [ ]:
#Посчитаем длину следующего вектора:
vec = np.array([3, 4])
#Для начала воспользуемся формулой: возведём все элементы в квадрат, посчитаем их сумму, 
# а затем найдём квадратный корень. Найдите все перечисленные операции в данном коде:
length = np.sqrt(np.sum(vec ** 2))
print(length)
# 5.0
#Но можно было поступить проще. В NumPy есть специальный подмодуль linalg, 
# который позволяет производить операции из линейной алгебры.
#Для вычисления длины вектора нам потребуется функция norm:
length = np.linalg.norm(vec)
print(length)
# 5.0

#Реализуем вычисление расстояния в коде. Сначала — «сложным» способом напрямую из формулы:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
# 12.206555615733702
#А теперь применим более простой способ — используем уже известную нам функцию np.linalg.norm:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702

#Реализуем это в коде (по-английски скалярное произведение называют dot — точечный — или scalar product,
# отсюда и такое название переменной):
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0
#Наверное, вы уже догадались, что в NumPy есть множество встроенных функций, поэтому возник резонный вопрос:
# можно ли проще и вообще без формул? Да! Для этого используют функцию np.dot(x, y):
scalar_product = np.dot(vec1, vec2)
scalar_product
# 250.0
#Скалярное произведение также имеет широкое применение в математике и других операциях с векторами. 
# В частности, равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)
# 0
#Здесь были специально заданы векторы, параллельные осям  и  (так как одна из координат в них равна нулю).
#Они перпендикулярны, как перпендикулярны соответствующие оси, а скалярное произведение действительно равно нулю.
#В целом, скалярное произведение часто используется для определения угла между векторами.

In [2]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])
#Векторы в геометрии называются сонаправленными, если они коллинеарны и их направления совпадают.
#На практике есть несколько способов определить сонаправленность векторов.
#Один из них: сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов.
len_a = np.sqrt(np.sum(a**2))
len_b = np.linalg.norm(b)
len_c = np.linalg.norm(c)
print (len_a,len_b,len_c)
print (np.linalg.norm (a+b) == len_a + len_b)
print (np.linalg.norm (a+c) == len_a + len_c) #*
print (np.linalg.norm (c+b) == len_c + len_b)

#Найдите пару перпендикулярных векторов с помощью скалярного произведения (оно должно быть равно нулю).
scalar_product_a_b = np.sum (a*b)
scalar_product_a_c = np.dot (a,c)
scalar_product_b_c = np.sum (b*c)
print (scalar_product_a_b, scalar_product_a_c, scalar_product_b_c)

#Найдите пару векторов, расстояние между которыми больше 100.
dist_a_b = np.sqrt(np.sum((a-b)**2))
dist_a_c = np.linalg.norm(a-c)
dist_b_c = np.sqrt(np.sum((a-b)**2))
print (dist_a_b, dist_a_c, dist_b_c)

49.13247398615299 70.94363960215179 98.26494797230598
False
True
False
34 4828 68
85.901105930017 49.13247398615299 85.901105930017


In [9]:
#Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. 
#Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
# 1
np.max(vec)
# 28
#Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!
vec.mean()
# 10.75
print (np.mean(vec))

#5. Статистика
#5.1. Основные статистические характеристики
amin(a[, axis, out, keepdims, initial])
#Минимальное значение элементов массива. 
# Параметр axis позволяет указывать оси, вдоль которых необходим поиск минимальных значений.
amax(a[, axis, out, keepdims, initial])
#Максимальное значение в массиве. 
# Параметр axis позволяет указывать оси, вдоль которых необходим поиск максимальных значений.
nanmin(a[, axis, out, keepdims])
#Минимальное значение массива или минимальное значение вдоль указанной оси. 
# Элементы с значением np.nan игнорируются.
nanmax(a[, axis, out, keepdims])
#Максимальное значение массива или максимальное значение вдоль указанной оси. 
# Элементы с значением np.nan игнорируются.
numpy.ptp(a[, axis, out, keepdims])
#Возвращает диапазон значений ([max - min]) массива или указанной оси массива.
numpy.percentile(a, q[, axis, out, overwrite_input, interpolation, keepdims])
#Вычисляет q-й процентиль (перцентиль) значений элементов массива или элементов вдоль указанной оси.
numpy.nanpercentile(a, q[, axis, out, overwrite_input, interpolation, keepdims])
#Вычисление q-го процентиля (перцентиля) значений вдоль указанной оси массива. 
# Элементы с значением np.nan игнорируются.
numpy.quantile(a, q[, axis, out, overwrite_input, interpolation, keepdims])
#Вычисление q-го процентиля (перцентиля) значений вдоль указанной оси массива. 
# Элементы с значением np.nan игнорируются.
numpy.nanquantile(a, q[, axis, out, overwrite_input, interpolation, keepdims])
#Вычисление q-го процентиля (перцентиля) значений вдоль указанной оси массива. 
# Элементы с значением np.nan игнорируются.

#5.2. Средние и отклонения
median(a[, axis, out, overwrite_input, keepdims])
#Медиана значений элементов массива, расположенных вдоль указанной оси.
average(a[, axis, weights, returned])
#Средневзвешенное значений элементов массива расположенных вдоль указанной оси.
mean(a[, axis, dtype, out, keepdims])
#Среднее арифметическое значений элементов массива расположенных вдоль указанной оси.
std(a[, axis, dtype, out, ddof, keepdims])
#Стандартное отклонение значений элементов массива расположенных вдоль указанной оси.
var(a[, axis, dtype, out, ddof, keepdims])
#Дисперсия значений элементов массива расположенных вдоль указанной оси.
nanmedian(a[, axis, out, overwrite_input, …])
#Медиана значений элементов массива расположенных вдоль указанной оси. Элементы с значением NaN игнорируются.
nanmean(a[, axis, dtype, out, keepdims])
#Среднее арифметическое значений элементов массива расположенных вдоль указанной оси. 
# Элементы с значением NaN игнорируются.
nanstd(a[, axis, dtype, out, ddof, keepdims])
#Стандартное отклонение значений элементов массива расположенных вдоль указанной оси. 
# Элементы с значением NaN игнорируются.
nanvar(a[, axis, dtype, out, ddof, keepdims])
#Дисперсия значений элементов массива расположенных вдоль указанной оси. Элементы с значением NaN игнорируются.

#5.3. Корреляции
corrcoef(x[, y, rowvar, bias, ddof])
#Коэфициент корреляции Пирсона.
correlate(a, v[, mode])
#Взаимнокорреляционная функция двух одномерных последовательностей.
cov(m[, y, rowvar, bias, ddof, fweights, …])
#Ковариационная матрица.
#5.4. Гистограммы
histogram(a[, bins, range, normed, weights, …])
#Вычисление гистограммы набора данных.
histogram2d(x, y[, bins, range, normed, weights])
#Вычисление двумерной гистограммы двух наборов данных.
histogramdd(sample[, bins, range, normed, …])
#Вычисление N-мерной гистограммы N-го количества наборов данных.
bincount(x[, weights, minlength])
#Количество вхождений значений в массиве.
numpy.histogram_bin_edges(a, bins=10, range=None, weights=None)
#Значения для прямоугольников гистограммы.
digitize(x, bins[, right])
#Вычисление индексов числовых интервалов массива bins в которые входит 
# каждое последующее значение элемента массива x.

10.75
