In [4]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
# array([ 1,  5,  2,  9, 10])
print(type(arr))
# <class 'numpy.ndarray'> Название ndarray — это сокращение от n-dimensional array, n-мерный массив.

# Перечислить список из списков можно было и в одну строку, но на нескольких строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

<class 'numpy.ndarray'>


array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [23]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr.dtype
# dtype('int64')

arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)
arr[2] = 2000
#Теперь, если добавить в arr число больше 127 или меньше -128,
# оно потеряет исходное значение, как и при преобразовании к меньшему типу:
arr
# array([  1,   5, -48,   9,  10], dtype=int8)
arr[2] = 125.5
#Если добавить float в массив int, пропадёт десятичная часть:
arr
# array([  1,   5, 125,   9,  10], dtype=int8)
arr[2] = '12'
#Строку, которую можно преобразовать в число, можно сразу положить в массив.
# Она будет приведена к нужному типу автоматически:
arr
# array([ 1,  5, 12,  9, 10], dtype=int8)
"""arr[2] = 'test'"""
# ValueError: invalid literal for int() with base 10: 'test'
#Поменять тип данных во всём массиве можно с помощью тех же функций, 
# которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните 
# (например, np.int32 или np.float128):
arr = np.float64(arr)
arr
# array([ 1.,  5., 12.,  9., 10.], dtype=float64)
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
# array([12321, -1234,  3435,  -214,   100], dtype=int32)
#При преобразовании типов данных в массиве не забывайте о том, 
#что часть чисел может потерять смысл, если менять тип данных с более ёмкого на менее ёмкий:
arr = np.uint8(arr)
arr
# array([ 33,  46, 107,  42, 100], dtype=uint8)

array_1 = np.array ([345234, 876362.12, 0, -1000, 99999999])
array_1.dtype


dtype('float64')

In [22]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)
#Узнать размерность массива можно с помощью .ndim:
arr.ndim
# 1
nd_arr.ndim
# 2
#Узнать общее число элементов в массиве можно с помощью .size:
arr.size
# 5
nd_arr.size
# 9
#Форма или структура массива хранится в атрибуте .shape:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)
#Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:
arr.itemsize
# 1
nd_arr.itemsize
# 2

dtype('float64')

In [2]:
import numpy as np
zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])
#Создадим трёхмерный массив с формой 5x4x3 и типом float32:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

"""щё одной удобной функцией для создания одномерных массивов является arange. 
Она аналогична встроенной функции range, но обладает рядом особенностей. 
Вот её сигнатура: arange([start,] stop, [step,], dtype=None).
Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) 
являются необязательными:
start (входит в диапазон возвращаемых значений) задаёт начальное число;
stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
step задаёт шаг, с которым в массив добавляются новые значения.
В отличие от range, в функции arange все перечисленные параметры могут иметь тип float."""
np.arange(5)
# array([0, 1, 2, 3, 4])
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

"""np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически)."""
arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

#Создадим массив из десяти чисел между 1 и 2, не включая 2:
arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

#Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1


(5, 4, 3)
0.1111111111111111
0.1


In [8]:
import numpy as np
#С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? 
# Ответ округлите до двух знаков после точки.
array_1, step = np.linspace(-6, 21, 60, retstep=True, endpoint=True)
round (step,2)
#0.46
#С каким шагом сгенерируется массив из 60 чисел от -6 (включительно) до 21 (не включительно)?
# Ответ округлите до 2 знаков после точки.
array_1, step = np.linspace(-6, 21, 60, retstep=True, endpoint=False)
round (step,2)


0.45